name: 'Release with HEMTT'
description: 'Build your mod with HEMTT.'
branding:
  icon: 'activity'
  color: 'orange'

inputs:
  zip_build:
      description: 'Zip the build'
      required: false
      default: true

outputs:
  zip_path:
    description: 'Relative path of packed mod'
  zip_name:
    description: 'Name of packed mod (without file extension)'

runs:
  using: 'node12'
  main: 'dist/index.js'
